In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("upwork-jobs.csv")
df.head(1)

,title,link,description,published_date,is_hourly,hourly_low,hourly_high,budget,country
0,Experienced Media Buyer For Solar Pannel and R...,https://www.upwork.com/jobs/Experienced-Media-...,We’re looking for a talented and hardworking a...,2024-02-17 09:09:54+00:00,False,NaN,NaN,500.0,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53058 entries, 0 to 53057
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           53058 non-null  object
 1   link            53058 non-null  object
 2   description     53058 non-null  object
 3   published_date  53058 non-null  object
 4   is_hourly       44829 non-null  object
 5   hourly_low      22956 non-null  float64
 6   hourly_high     22161 non-null  float64
 7   budget          21873 non-null  float64
 8   country         51917 non-null  object
dtypes: float64(3), object(6)
memory usage: 3.6+ MB

In [9]:
df.isnull().sum()

title                 0
link                  0
description           0
published_date        0
is_hourly          8229
hourly_low        30102
hourly_high       30897
budget            31185
country            1141
dtype: int64

In [10]:
# Fill 'is_hourly' column with mode (most frequent value)
df['is_hourly'].fillna(df['is_hourly'].mode()[0], inplace=True)

In [12]:
# Fill 'hourly_low' column with mean
hourly_low_mean = df['hourly_low'].mean()
df['hourly_low'].fillna(hourly_low_mean, inplace=True)

In [13]:

# Fill 'hourly_high' column with mean
hourly_high_mean = df['hourly_high'].mean()
df['hourly_high'].fillna(hourly_high_mean, inplace=True)

In [14]:


# Fill 'budget' column with mean
budget_mean = df['budget'].mean()
df['budget'].fillna(budget_mean, inplace=True)

# Now the null values in the specified columns should be filled as per your requirements

In [15]:
df.isnull().sum()

title                0
link                 0
description          0
published_date       0
is_hourly            0
hourly_low           0
hourly_high          0
budget               0
country           1141
dtype: int64

In [16]:
len(df)

53058

In [17]:
df.dropna(subset=['country'], inplace=True)

In [18]:
len(df)

51917

In [19]:
df.isnull().sum()

title             0
link              0
description       0
published_date    0
is_hourly         0
hourly_low        0
hourly_high       0
budget            0
country           0
dtype: int64

In [21]:
df.head()

,title,link,description,published_date,is_hourly,hourly_low,hourly_high,budget,country
1,Full Stack Developer,https://www.upwork.com/jobs/Full-Stack-Develop...,Job Title: Full Stack DeveloperWe are seeking ...,2024-02-17 09:09:17+00:00,False,17.467895,41.60805,1100.000000,United States
2,SMMA Bubble App,https://www.upwork.com/jobs/SMMA-Bubble-App_%7...,I need someone to redesign my bubble.io site t...,2024-02-17 09:08:46+00:00,True,10.000000,30.00000,746.263521,United States
3,Talent Hunter Specialized in Marketing,https://www.upwork.com/jobs/Talent-Hunter-Spec...,Join Our Growing Team!We are an innovative com...,2024-02-17 09:08:08+00:00,True,17.467895,41.60805,746.263521,United States
4,Data Engineer,https://www.upwork.com/jobs/Data-Engineer_%7E0...,We are looking for a resource who can work par...,2024-02-17 09:07:42+00:00,False,17.467895,41.60805,650.000000,India
5,SEO for Portuguese Psychologist site,https://www.upwork.com/jobs/SEO-for-Portuguese...,Looking for a SEO who can help me improve my ...,2024-02-17 09:07:41+00:00,True,17.467895,41.60805,746.263521,Portugal

In [24]:
#checking for SEO related jobs
df[df["title"].str.contains("SEO")]

,title,link,description,published_date,is_hourly,hourly_low,hourly_high,budget,country
5,SEO for Portuguese Psychologist site,https://www.upwork.com/jobs/SEO-for-Portuguese...,Looking for a SEO who can help me improve my ...,2024-02-17 09:07:41+00:00,True,17.467895,41.60805,746.263521,Portugal
87,Certified personal trainer / physical therapis...,https://www.upwork.com/jobs/Certified-personal...,We are seeking a certified personal trainer or...,2024-02-18 04:34:44+00:00,False,17.467895,41.60805,100.000000,United States
142,Copywriter - SEO friendly articles on tech inn...,https://www.upwork.com/jobs/Copywriter-SEO-fri...,"I'm seeking a talented Freelance Copywriter t,...",2024-02-18 09:13:09+00:00,True,17.467895,41.60805,746.263521,Israel
167,high-end SEO friendly website for watch buyers,https://www.upwork.com/jobs/high-end-SEO-frien...,Project Description:We are seeking an experien...,2024-02-19 00:41:41+00:00,False,17.467895,41.60805,400.000000,Canada
266,Formation sur YOAST SEO,https://www.upwork.com/jobs/Formation-sur-YOAS...,Bonjour.Je suis à la recherche d'un formateur ...,2024-02-17 16:00:16+00:00,True,16.000000,18.00000,746.263521,United Kingdom
...,...,...,...,...,...,...,...,...,...
52743,Amazon FBA new product SEO JUMPSTART,https://www.upwork.com/jobs/Amazon-FBA-new-pro...,Need someone who can bring Amazon store to lif...,2024-02-16 07:33:42+00:00,True,5.000000,10.00000,746.263521,United States
52867,In need of SEO for Private Practice Website,https://www.upwork.com/jobs/need-SEO-for-Priva...,I am in need of someone to search engine optim...,2024-02-20 03:31:34+00:00,True,17.467895,41.60805,746.263521,United States
52907,German-speaking Content Writer for SEO,https://www.upwork.com/jobs/German-speaking-Co...,We are seeking a German-speaking content write...,2024-02-23 14:02:57+00:00,False,17.467895,41.60805,65.000000,Hungary
52917,Implement SEO Strategy for Italian Shoe Brand ...,https://www.upwork.com/jobs/Implement-SEO-Stra...,We are seeking a skilled SEO/SEM specialist wh...,2024-02-23 10:26:08+00:00,True,50.000000,100.00000,746.263521,Italy
53018,Do A Fully SEO Focused Competitor Analysis For...,https://www.upwork.com/jobs/Fully-SEO-Focused-...,"So, I am developing a new business in the UAE ...",2024-02-19 10:20:02+00:00,False,17.467895,41.60805,150.000000,Pakistan

In [28]:
#making them simple 
# Replace cells containing 'SEO' with 'SEO' and remove extra strings

df['title'] = df['title'].str.replace('.*SEO.*', 'SEO', regex=True)

In [34]:
df["title"].value_counts()

SEO                                                                             985
Virtual Assistant                                                                99
Social Media Manager                                                             89
Graphic Designer                                                                 63
Simple copy and paste data from a webpage into excel                             49
                                                                               ...
Creative video editor and graphics designer for a global brand                    1
Athletic Wear Production Manager                                                  1
Ghostwriter with experience in tech industry to write series of white papers      1
Presentation Template for Nonprofit organization                                  1
Make room and price modifications to Hotel booking plugin                         1
Name: title, Length: 45174, dtype: int64

In [39]:
df[df["title"].str.contains("Graphic Designer")]

,title,link,description,published_date,is_hourly,hourly_low,hourly_high,budget,country
173,Graphic Designer,https://www.upwork.com/jobs/Graphic-Designer_%...,We are seeking a talented Designer to help wit...,2024-02-19 00:39:10+00:00,False,17.467895,41.60805,150.000000,Australia
263,Graphic Designer - Needed for logo creation,https://www.upwork.com/jobs/Graphic-Designer-N...,Hello Graphic Designers!I am a small business ...,2024-02-17 16:00:33+00:00,False,17.467895,41.60805,150.000000,United States
587,Graphic Designer for Bauernaufstand Vektorgrafik,https://www.upwork.com/jobs/Graphic-Designer-f...,We are looking for a skilled graphic designer ...,2024-02-18 14:12:37+00:00,False,17.467895,41.60805,35.000000,Germany
588,German-speaking T-Shirt Vector Graphic Designer,https://www.upwork.com/jobs/German-speaking-Sh...,We are in need of a talented graphic designer ...,2024-02-18 14:12:36+00:00,False,17.467895,41.60805,35.000000,Germany
613,Graphic Designers Needed for Beverage Company ...,https://www.upwork.com/jobs/Graphic-Designers-...,We are looking for a team of graphic designers...,2024-02-14 19:44:12+00:00,True,15.000000,100.00000,746.263521,United States
...,...,...,...,...,...,...,...,...,...
52801,Creative Graphic Designer for Innovative Projects,https://www.upwork.com/jobs/Creative-Graphic-D...,Are you a passionate and versatile Graphic Des...,2024-02-16 14:44:16+00:00,True,50.000000,150.00000,746.263521,Pakistan
52851,Graphic Designer to create printable inserts f...,https://www.upwork.com/jobs/Graphic-Designer-c...,We own a liquor and cigar shop in central Kans...,2024-02-14 16:27:14+00:00,True,35.000000,50.00000,746.263521,United States
52978,Creative Graphic Designer for Web Development ...,https://www.upwork.com/jobs/Creative-Graphic-D...,We are a newly established web development com...,2024-02-14 18:45:26+00:00,True,50.000000,150.00000,746.263521,Pakistan
53003,Graphic Designer for Amazon Listing and A+ EBC...,https://www.upwork.com/jobs/Graphic-Designer-f...,Job Description:Introduction:We are looking fo...,2024-02-19 10:24:45+00:00,False,17.467895,41.60805,250.000000,Romania
53034,Junior Graphic Designer needed to resize Photo...,https://www.upwork.com/jobs/Junior-Graphic-Des...,I need to resize Artboards in Adobe Photoshop....,2024-02-16 17:30:29+00:00,True,8.000000,16.00000,746.263521,South Africa

In [49]:
df['title'] = df['title'].str.replace('.*Graphic Designer.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*Graphic Design.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*Logo Design.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*Logo design.*', 'Graphic Designer', regex=True)
df["title"].value_counts().to_csv('title_counts.csv',header=True)

In [55]:
df['title'] = df['title'].str.replace('.*design.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*Design.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*Logo.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*logo.*', 'Graphic Designer', regex=True)
df['title'] = df['title'].str.replace('.*LOGO.*', 'Graphic Designer', regex=True)

In [56]:
df["title"].value_counts().to_csv('title_counts.csv',header=True)